from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import uuid4

@dataclass(frozen=True)
class AttackPayload:
    """Payload generated by the attacker to bypass guardrails."""
    id: str
    prompt: str
    context: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)

@dataclass(frozen=True)
class TargetResponse:
    """Response received from the target API."""
    id: str
    payload_id: str
    response_text: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)

@dataclass(frozen=True)
class EvaluationResult:
    """Judge's evaluation of the target's response."""
    id: str
    payload_id: str
    response_id: str
    is_bypassed: bool
    reasoning: str
    criteria: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)

@dataclass(frozen=True)
class AttackPath:
    """A sequence of payloads and responses that led to a bypass."""
    id: str
    target: str
    steps: List[Dict[str, Any]] = field(default_factory=list)
    timestamp: datetime = field(default_factory=datetime.utcnow)

@dataclass(frozen=True)
class Evidence:
    """Proof of a finding or hypothesis validation."""
    content: str
    source: str
    content_hash: str
    signature: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass(frozen=True)
class Finding:
    """A security issue or interesting discovery on an asset."""
    title: str
    severity: str  # critical, high, medium, low, info
    description: str
    evidence_ids: List[str] = field(default_factory=list)
    vulnerability_type: Optional[str] = None
    path: Optional[str] = None
    param: Optional[str] = None


# ────────────────────────────────────────────────────────────────────────────
# Guardrail models (guardrail-pivot slice 2, AD-12)
# ────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True, kw_only=True)
class IncomingPrompt:
    """Prompt submitted by a client for guardrail evaluation."""
    prompt: str
    model: str
    stream: bool = False
    id: str = field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True, kw_only=True)
class UpstreamResponse:
    """Response received from the upstream LLM."""
    id: str
    decision_id: str
    status_code: int
    body: Dict[str, Any]
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True, kw_only=True)
class Verdict:
    """Judge evaluation result for a prompt."""
    verdict: str  # "safe" | "blocked"
    reason: str
    confidence: float


@dataclass(frozen=True, kw_only=True)
class PolicyDecision:
    """Outcome of policy evaluation for a prompt."""
    action: str  # "allow" | "block"
    reason_code: Optional[str] = None
    rule_id: Optional[str] = None
