from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional, Any

@dataclass(frozen=True)
class AttackPayload:
    """Payload generated by the attacker to bypass guardrails."""
    id: str
    prompt: str
    context: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)

@dataclass(frozen=True)
class TargetResponse:
    """Response received from the target API."""
    id: str
    payload_id: str
    response_text: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)

@dataclass(frozen=True)
class EvaluationResult:
    """Judge's evaluation of the target's response."""
    id: str
    payload_id: str
    response_id: str
    is_bypassed: bool
    reasoning: str
    criteria: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)

@dataclass(frozen=True)
class AttackPath:
    """A sequence of payloads and responses that led to a bypass."""
    id: str
    target: str
    steps: List[Dict[str, Any]] = field(default_factory=list)
    timestamp: datetime = field(default_factory=datetime.utcnow)

@dataclass(frozen=True)
class Evidence:
    """Proof of a finding or hypothesis validation."""
    content: str
    source: str
    content_hash: str
    signature: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass(frozen=True)
class Finding:
    """A security issue or interesting discovery on an asset."""
    title: str
    severity: str  # critical, high, medium, low, info
    description: str
    asset_id: str  # References an Asset (domain or ip)
    evidence_ids: List[str] = field(default_factory=list)
    vulnerability_type: Optional[str] = None
    path: Optional[str] = None
    param: Optional[str] = None
