apiVersion: v2
name: shinkiro
description: Ephemeral Cyber Deception & Attacker Intelligence Mesh
type: application
version: 0.4.0
appVersion: "0.4.0"
keywords:
  - security
  - honeypot
  - deception
  - cyber-intelligence
  - mitre-attack
home: https://github.com/Haiagari/shinkiro
maintainers:
  - name: Haiagari
