package defense

import (
	"fmt"
	"strings"
)

type Format string

const (
	FormatIPTables Format = "iptables"
	FormatNFTables Format = "nftables"
	FormatCIDR     Format = "cidr"
)

// GenerateRules exports blocked IPs into ready-to-apply firewall commands
func GenerateRules(ips []string, format Format) string {
	var sb strings.Builder

	switch format {
	case FormatIPTables:
		sb.WriteString("# Generated by Shinkiro (Active Defense Engine)\n")
		for _, ip := range ips {
			sb.WriteString(fmt.Sprintf("iptables -A INPUT -s %s -j DROP\n", ip))
		}
	case FormatNFTables:
		sb.WriteString("add table inet shinkiro_filter\n")
		sb.WriteString("add set inet shinkiro_filter blackhole { type ipv4_addr; }\n")
		for _, ip := range ips {
			sb.WriteString(fmt.Sprintf("add element inet shinkiro_filter blackhole { %s }\n", ip))
		}
		sb.WriteString("add rule inet shinkiro_filter input ip saddr @blackhole drop\n")
	case FormatCIDR:
		for _, ip := range ips {
			sb.WriteString(fmt.Sprintf("%s/32\n", ip))
		}
	default:
		for _, ip := range ips {
			sb.WriteString(fmt.Sprintf("%s\n", ip))
		}
	}

	return sb.String()
}
