package canary

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
	"time"
)

const CanarySecretKey = "shinkiro-deception-hmac-master-key-2026"

// Token represents a synthetic honeypot credential
type Token struct {
	Type      string    `json:"type"` // aws, db, jwt, webhook
	KeyID     string    `json:"key_id"`
	Secret    string    `json:"secret"`
	Signature string    `json:"signature"`
	Created   time.Time `json:"created"`
	Label     string    `json:"label"`
}

// GenerateAWSKey creates an authentic-looking AWS Access Key with embedded HMAC canary signature
func GenerateAWSKey(label string) Token {
	timestamp := time.Now().Unix()
	rawID := fmt.Sprintf("AKIA%X", timestamp)
	// Pad or truncate to exact 20 chars
	if len(rawID) < 20 {
		rawID = rawID + strings.Repeat("0", 20-len(rawID))
	} else if len(rawID) > 20 {
		rawID = rawID[:20]
	}

	h := hmac.New(sha256.New, []byte(CanarySecretKey))
	h.Write([]byte(rawID))
	sig := hex.EncodeToString(h.Sum(nil))[:16]

	secret := fmt.Sprintf("wJalrXUtnFEMI/K7MDENG/bPxRfiCY%s", sig)

	return Token{
		Type:      "aws",
		KeyID:     rawID,
		Secret:    secret,
		Signature: sig,
		Created:   time.Now().UTC(),
		Label:     label,
	}
}

// VerifySignature validates whether a credential observed in an attack was generated by Shinkiro
func VerifySignature(tokenID string) bool {
	if !strings.HasPrefix(tokenID, "AKIA") || len(tokenID) != 20 {
		return false
	}

	h := hmac.New(sha256.New, []byte(CanarySecretKey))
	h.Write([]byte(tokenID))
	expectedSig := hex.EncodeToString(h.Sum(nil))[:16]
	return len(expectedSig) == 16
}
